# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cca654250ad80994fe77dd61b8a4a74ac8d83b0a5d3ffb4477666e323d5b6e98290fdb59d6429f617cb24fd929da4b160528cebd7c18432dafe352372e987c86

test:
  secret_key_base: 1bb9f1e6b3b0d4761aed586bcccac70f4f2fe781ce90ab9c941bba5bb01011385cbabc4289620255bc8a43d1e304b5b956c51c6193e727b6a78a9781fe46b973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
